# Server
server.port=${PORT:8081}
spring.application.name=restapi

# PostgreSQL Database Connection
spring.datasource.username=${PGUSER:postgres}
spring.datasource.password=${PGPASSWORD:password}
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/restapi}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Actuator
management.endpoints.web.exposure.include=health,info